apiVersion: v1
kind: ConfigMap
metadata:
  name: tracking-api-endpoints
  namespace: {{ .Values.namespace.name }}
  labels:
    {{- include "tracking-app.labels" . | nindent 4 }}
data:
  DELIVERY_API_DOMAIN: {{ .Values.config.deliveryApiDomain | quote }}
  DISPATCH_API_DOMAIN: {{ .Values.config.dispatchApiDomain | quote }}
  DRIVER_APP_DOMAIN_CA: {{ .Values.config.driverAppDomainCa | quote }}
  DRIVER_APP_DOMAIN_US: {{ .Values.config.driverAppDomainUs | quote }}
