{{- if .Values.targetGroupBinding.enabled }}
apiVersion: elbv2.k8s.aws/v1beta1
kind: TargetGroupBinding
metadata:
  name: tracking-app
  namespace: {{ .Values.namespace.name }}
  labels:
    {{- include "tracking-app.labels" . | nindent 4 }}
  annotations:
    helm.sh/hook: post-install,post-upgrade
    helm.sh/hook-weight: "0"
    helm.sh/hook-delete-policy: before-hook-creation
spec:
  serviceRef:
    name: tracking-app
    port: {{ .Values.service.port }}
  targetGroupARN: {{ .Values.targetGroupBinding.arn | quote }}
  targetType: ip
  ipAddressType: ipv4
{{- end }}
